name: Deploy Sphinx Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.2"

      - name: Install application
        run: poetry install

      - name: Build documentation
        run: poetry run sphinx-build -b html docs/source docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          user_email: 'markpbaggett@gmail.com'
          user_name: 'markpbaggett'
